theme: jekyll-theme-minimal
title: Testiautomaatio-Demo 2026
description: Ohjelmistotuotannon kurssiprojekti. Testaus, arkkitehtuuri ja laatu samassa paketissa.

# Tämä lisää "View on GitHub" -napin automaattisesti sivupalkkiin
github:
  is_project_page: true
