remote_theme: just-the-docs/just-the-docs
title: Testiautomaatio-Demo 2026
description: Ohjelmistotuotannon kurssiprojekti.

# Aktivoidaan tumma tila (Full Dark Mode)
color_scheme: dark

# Navigointiasetukset
nav_enabled: true
footer_content: "© 2026 Supsupwubwub - SE Course"
